New about page
PlebeianTech/plebeian-market pull request #313
Opened 2023-09-19 15:19 UTC by miguepollo

This is the new about page, give a look and tell me if something needs to be changed.

2023-09-19 18:48 UTC, ibz requested changes

2023-09-19 18:48 UTC, ibz commented on web/frontoffice/src/routes/about/+page.svelte
> +                    <div class="uppercase my-2 font-bold text-sm">Description</div>
Need job title here...

2023-09-19 18:48 UTC, ibz commented on web/frontoffice/src/routes/about/+page.svelte
> +                    <div class="uppercase my-2 font-bold text-sm">Description</div>
Need job title...

2023-09-19 18:48 UTC, ibz commented on web/frontoffice/src/routes/about/+page.svelte
> +                    <div class="uppercase my-2 font-bold text-sm">Bitcoiner , remnant and shadowy super coder</div>
No space before ","...

2023-09-19 18:48 UTC, ibz commented on web/frontoffice/src/routes/about/+page.svelte
> +                <img src="/team/MTC.jpg" alt=""/>
All other files are lowercase, maybe we should keep it that way for consistency?

2023-09-20 16:01 UTC, miguepollo commented
Yes of course 
![image](https://github.com/PlebeianTech/plebeian-market/assets/127879645/c3d84619-99e1-4c45-bcd3-9a7365c3561a)

2023-09-20 16:20 UTC, ktecho commented
@miguepollo Also, could you please center the text in the last box so the "you?" and "bitcoiner..." texts are in the middle of the box?

2023-09-20 16:46 UTC, miguepollo commented
Ok

2023-09-21 17:58 UTC, ktecho commented
@ibz LGTM

2023-09-23 15:45 UTC, merged